# Generated by Django 4.1.3 on 2022-11-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valA', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('valB', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('valC', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('valD', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('strA', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
